name: hellotr
version: 1
summary: Qt Hello World example
description: A simple Qt example

apps:
  hellotr:
    command: qt5-launch hellotr
    plugs:
      - x11

parts:
  hellotr:
    plugin: qmake
    source: src/
    build-packages:
      - qtbase5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
    after: [qt5conf] # A wiki part
