name: fancybrowser
version: 1
summary: Qt Fancy Browser Example
description: A simple web browser

apps:
  fancybrowser:
    command: qt5-launch fancybrowser
    plugs:
      - network
      - network-bind
      - unity7

parts:
  application:
    plugin: qmake
    source: src/
    build-packages:
      - qtbase5-dev
      - libqt5webkit5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
    after: [qt5conf] # A wiki part
